### ISSUE TITLE
心跳包相关功能?

### ISSUE THREAD

**Issue by dtboy1995** [lp0int/TcpSocketLib#1]
首先感谢作者，您有计划添加心跳包相关的功能吗？谢谢

**Comment by lp0int** [comment]
Hi，心跳动作应该是一个双向的操作，可以在收到服务端的心跳后，调用sendMsg来实现心跳的功能

**Comment by dtboy1995** [comment]
作者您好，经过我实测的话，重连有一些问题，就是我直接断开tcp server的话，用您的库是重连不成功的

**Comment by lp0int** [comment]
方便的话可以把具体的操作发邮件给我吗？xiaoawl23@hotmail.com

**Comment by dtboy1995** [comment]
其实我这边测试的很简单，就是用·
- nodejs起了个tcp server
- 用您的库去连 启动之前已经设置重连方法为true
- 最后ctrl c 关掉tcp server
- 再启动tcp server 等待Android client重连

然后就没有然后了
重连的情况很多，比如切换网络，tcp server 本身出现问题， tcp server 直接被杀死，Android端切网等，有时间我会一一测试给您反馈的。
